version: "3"
networks:
  maquequette:
    external: false

services: 
  laravelserviceaws:
    build:
      context: ./ServiceAws
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8001:81"


  symfonyservicecrud:
    build:
      context: ./ServiceCrud
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8002:82"
    volumes:
      - ./ServiceCrud/symfony:/var/www/html